#!/usr/bin/env sh
set -e

./gradlew --quiet spotlessApply

if ! git diff --quiet; then
  git add -A
  git commit -m "style: apply Spotless" --no-verify
fi

./gradlew --quiet detekt
./gradlew --quiet clean check
echo "pre-push OK"