naming:
  ClassNaming:
    active: true
    classPattern: '^(?!.*[A-Z]{2})[A-Z][A-Za-z0-9]*$'

  FunctionNaming:
    active: true
    functionPattern: '^(?!.*[A-Z]{2})[a-z][A-Za-z0-9]*$'
    ignoreAnnotated: ['Test']

  VariableNaming:
    active: true
    variablePattern: '^(?!.*[A-Z]{2})[a-z][A-Za-z0-9]*$'

style:
  MaxLineLength:
    active: true
    maxLineLength: 400
    excludePackageStatements: true
    excludeImportStatements: true
    excludeCommentStatements: false

  ReturnCount:
    active: true
    max: 10

  LoopWithTooManyJumpStatements:
    active: false

complexity:
  LongParameterList:
    active: true
    allowedFunctionParameters: 8

  CyclomaticComplexMethod:
    active: true
    allowedComplexity: 25

  TooManyFunctions:
    active: true
    allowedFunctionsPerClass: 20
    allowedFunctionsPerInterface: 20


exceptions:
  TooGenericExceptionCaught:
    active: true
    excludes: ['**/runner/src/main/kotlin/org/printscript/runner/**']
    allowedExceptionNameRegex: '^(_|(ignore|expected).*)'
